import createFetchClient from 'openapi-fetch';
import createClient from 'openapi-react-query';

import type { paths } from './generated-schema'; // generated by openapi-typescript

export const fetchClient = createFetchClient<paths>({
  baseUrl: import.meta.env.VITE_APP_CORE_USER_SERVICE_URL,
  headers: {
    'x-tenant-id': 'iff',
  },
});

fetchClient.use({
  onResponse: ({ response }) => {
    const data = response.clone().json();

    // Throw the standard error message if it exists
    const errorMessage =
      data &&
      typeof data === 'object' &&
      'error' in data &&
      typeof data.error === 'string'
        ? data.error
        : null;

    if (errorMessage) {
      throw new Error(errorMessage);
    }
  },
});

export const $api = createClient(fetchClient);
