import createFetchClient from 'openapi-fetch';
import createClient from 'openapi-react-query';

import type { paths } from './generated-schema'; // generated by openapi-typescript

export const fetchClient = createFetchClient<paths>({
  baseUrl: import.meta.env.VITE_APP_CORE_USER_SERVICE_URL,
});

export const $api = createClient(fetchClient);
