import createFetchClient from 'openapi-fetch';
import createClient from 'openapi-react-query';

import type { paths } from './generated-schema'; // generated by openapi-typescript

export const fetchClient = createFetchClient<paths>({
  baseUrl: 'http://localhost:8080',
});

export const $api = createClient(fetchClient);
